name: Deploy

on:
  push:
    paths:
      - "example/**"
      - "!example/README.md"

permissions: 
  contents: write

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies and build
        run: |
          pnpm install
          pnpm --filter solid-hcaptcha build
          pnpm --filter solid-hcaptcha-example build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: example/dist
